language: ruby

rvm:
 - 2.0.0
 - 2.1
 - 2.2.7
 - 2.3.4
 - 2.4.1
 - ruby-head
 - rbx-2

gemfile:
  - gemfiles/Gemfile-rails-4-2

sudo: false
cache: bundler

script: bundle exec rake test

matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: ruby-head
  fast_finish: true
  include:
    - gemfile: gemfiles/Gemfile-rails-5-0
      rvm: 2.2.7
    - gemfile: gemfiles/Gemfile-rails-5-1
      rvm: 2.2.7
    - gemfile: gemfiles/Gemfile-rails-5-0
      rvm: 2.3.4
    - gemfile: gemfiles/Gemfile-rails-5-1
      rvm: 2.3.4
    - gemfile: Gemfile
      rvm: 2.3.4
    - gemfile: gemfiles/Gemfile-rails-5-0
      rvm: 2.4.1
    - gemfile: gemfiles/Gemfile-rails-5-1
      rvm: 2.4.1
    - gemfile: gemfiles/Gemfile-rails-edge
      rvm: 2.4.1
    - gemfile: Gemfile
      rvm: 2.4.1
    - gemfile: gemfiles/Gemfile-rails-5-0
      rvm: ruby-head
    - gemfile: gemfiles/Gemfile-rails-5-1
      rvm: ruby-head
    - gemfile: gemfiles/Gemfile-rails-edge
      rvm: 2.5.3
    - gemfile: Gemfile
      rvm: ruby-head
